# fly.toml app configuration file generated for ollama-frosty-violet-8862 on 2024-09-16T17:07:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ollama-frosty-violet-8862'
primary_region = 'ord'

[build]
  image = 'ollama/ollama:latest'

[[mounts]]
  source = 'ollama'
  destination = '/root/.ollama'
  initial_size = '10gb'

[http_service]
  internal_port = 11434
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  size = 'performance-8x'
  memory = '16gb'
  gpu_kind = 'l40s'
